version: '3.8'

services:
  db:
    container_name: db
    image: postgres:15.1-alpine
    volumes:
      - /var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 20s
      retries: 100
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - web_network
  web:
    container_name: web_fastapi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code/
    env_file:
      - .env
    entrypoint: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - web_network
    ports:
     - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  redis:
    image: redis:latest
    container_name: redis_latest
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - web_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 20s
      retries: 20

networks:
  web_network:
    name: web_network
