version: '3.8'

services:
  db:
    container_name: db
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 20s
      retries: 100
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - web_network
  web:
    container_name: web_fastapi
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    entrypoint: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - web_network
    ports:
     - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

networks:
  web_network:
    name: web_network
