version: '3.8'

services:
  db:
    container_name: db-ylab
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - web_network
networks:
  web_network:
    name: web_network