version: '3.8'

services:
  test_db:
    container_name: test_db
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_DB=postgres_test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 20s
      retries: 100
    ports:
      - "5433:5432"
    expose:
      - 5432
    networks:
      - test_network
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   entrypoint: >
  #     sh -c "
  #       uvicorn app.main:app --host 0.0.0.0 --reload
  #     "
  #   networks:
  #     - test_network
  #   ports:
  #    - "8000:8000"
  #   depends_on:
  #     db:
  #       condition: service_healthy

networks:
  test_network:
    driver: bridge
